[project]
name = "py-note"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"

dependencies = [
  "mkdocs>=1.5.3",
  "mkdocs-material>=9.5.35",
  "python-dotenv>=1.0.0",
  "mkdocs-static-i18n>=1.2.0",
  "mkdocs-glightbox>=0.3.5",
]
