[project]
name = "py-note"
version = "0.1.0"
description = "python note"
readme = "README.md"
requires-python = ">=3.14"

dependencies = [
  "mkdocs>=1.6.1",
  "mkdocs-material>=9.7.0",
  "mkdocs-glightbox>=0.5.2",
]
